### ISSUE TITLE
Python 3 compatiblity

### ISSUE THREAD

**Issue by sebastian-nagel** [commoncrawl/cc-mrjob#11]
This library does not run on Python 3.x:
- along with minor syntax fixes
- the [warc module](https://github.com/erroneousboat/warc3) dependency needs a change, cf. internetarchive/warc#25, internetarchive/warc#26, [erroneousboat/warc3](https://github.com/erroneousboat/warc3)

**Comment by hungrymonkey** [comment]
I am just here to document the obvious. I know this issue has already been known.

https://mail.python.org/pipermail/python-ideas/2009-March/003821.html
https://stackoverflow.com/questions/9047745/where-is-the-builtin-module-in-python3-why-was-it-renamed

```
Traceback (most recent call last):
  File "print_all_urls.py", line 3, in <module>
    import warc
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/warc/__init__.py", line 10, in <module>
    from .arc import ARCFile, ARCRecord, ARCHeader
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/warc/arc.py", line 7, in <module>
    import __builtin__
```

**Comment by sebastian-nagel** [comment]
See #31.
