### ISSUE TITLE
subprocess failed with code 143

### ISSUE THREAD

**Issue by CryptoKR** [commoncrawl/cc-mrjob#27]
I was running a cluster  when the job Failed. Below is the output. I've tried a few times and it keeps getting the same results, does anyone know why?
 

 RUNNING for 0:45:10
  RUNNING for 0:45:41
  RUNNING for 0:46:13
  FAILED
Cluster j-2HXHFC0G6T7SO is TERMINATING: Shut down as step failed
Attempting to fetch counters from logs...
Waiting for cluster (j-2HXHFC0G6T7SO) to terminate...
  TERMINATING
  TERMINATING
  TERMINATING
  TERMINATED_WITH_ERRORS
Looking for step log in s3://my-bucket111222333/tmp/logs/j-2HXHFC0G6T7SO/steps/s-2AIZSU46X94HC...
  Parsing step log: s3://my-bucket111222333/tmp/logs/j-2HXHFC0G6T7SO/steps/s-2AIZSU46X94HC/syslog.2020-01-08-14.gz
  Parsing step log: s3://my-bucket111222333/tmp/logs/j-2HXHFC0G6T7SO/steps/s-2AIZSU46X94HC/syslog.gz

Probable cause of failure:

PipeMapRed failed!
java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 143
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:325)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:538)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:455)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

(from lines 64-77 of s3://my-bucket111222333/tmp/logs/j-2HXHFC0G6T7SO/containers/application_1578495208815_0001/container_1578495208815_0001_01_397743/syslog.gz)

**Comment by sebastian-nagel** [comment]
The message in the syslog only indicates that one map task has failed. The reason for the failure should be logged in the stderr of the container running the task - it could be a Python exception not properly caught. See #22 how to find the right stderr log file, or just grep them all (maybe only the tail) to find the reason.
